# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fafe2f4a6ae465f74dd227f0860121b0968914b8e3ee5662483af79768925a3c5a931d583bced854547aca6f47022baa115b6677716022bebd455164602fecc

test:
  secret_key_base: d88f8cffceba932e0431d87947669d85b8c692caf32487ee3c543053f8db947a923a01588cbec1ef9185590981d5f1877ed26bc4dceba059691de8431d00eb36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
